apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: aws-file-credentials
entity:
  driver_inputs:
   secret_refs:
      files:
        aws_creds:
          value: ${resources.config#aws-account.outputs.credentials_file}
    values:
      script: |-

        variable "region" {}

        terraform {
          required_providers {
            aws = {
              source = "hashicorp/aws"
            }
          }
        }

        provider "aws" {
          region     = var.region

          # The file is defined above. The provide will read the creds from this file.
          shared_credentials_files = ["aws_creds"]
        }
        
        output "bucket" {
          value = aws_s3_bucket.bucket.bucket
        }

        output "region" {
          value = var.region
        }

        resource "aws_s3_bucket" "bucket" {
          bucket = "$\{replace("${context.res.id}", "^.*\.", "")}-standard-${context.env.id}-${context.app.id}-${context.org.id}"
          tags = {
            Humanitec = true
          }
        }

      variables:
        region: us-east-1
  driver_type: humanitec/terraform
  name: aws-file-credentials
  type: s3

  # Supply matching criteria
  criteria: {}